/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Datasource } from "./Datasource";
import { DatasourceCountArgs } from "./DatasourceCountArgs";
import { DatasourceFindManyArgs } from "./DatasourceFindManyArgs";
import { DatasourceFindUniqueArgs } from "./DatasourceFindUniqueArgs";
import { CreateDatasourceArgs } from "./CreateDatasourceArgs";
import { UpdateDatasourceArgs } from "./UpdateDatasourceArgs";
import { DeleteDatasourceArgs } from "./DeleteDatasourceArgs";
import { DatasourceService } from "../datasource.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Datasource)
export class DatasourceResolverBase {
  constructor(
    protected readonly service: DatasourceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Datasource",
    action: "read",
    possession: "any",
  })
  async _datasourcesMeta(
    @graphql.Args() args: DatasourceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Datasource])
  @nestAccessControl.UseRoles({
    resource: "Datasource",
    action: "read",
    possession: "any",
  })
  async datasources(
    @graphql.Args() args: DatasourceFindManyArgs
  ): Promise<Datasource[]> {
    return this.service.datasources(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Datasource, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Datasource",
    action: "read",
    possession: "own",
  })
  async datasource(
    @graphql.Args() args: DatasourceFindUniqueArgs
  ): Promise<Datasource | null> {
    const result = await this.service.datasource(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Datasource)
  @nestAccessControl.UseRoles({
    resource: "Datasource",
    action: "create",
    possession: "any",
  })
  async createDatasource(
    @graphql.Args() args: CreateDatasourceArgs
  ): Promise<Datasource> {
    return await this.service.createDatasource({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Datasource)
  @nestAccessControl.UseRoles({
    resource: "Datasource",
    action: "update",
    possession: "any",
  })
  async updateDatasource(
    @graphql.Args() args: UpdateDatasourceArgs
  ): Promise<Datasource | null> {
    try {
      return await this.service.updateDatasource({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Datasource)
  @nestAccessControl.UseRoles({
    resource: "Datasource",
    action: "delete",
    possession: "any",
  })
  async deleteDatasource(
    @graphql.Args() args: DeleteDatasourceArgs
  ): Promise<Datasource | null> {
    try {
      return await this.service.deleteDatasource(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
