/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DatasourceService } from "../datasource.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DatasourceCreateInput } from "./DatasourceCreateInput";
import { Datasource } from "./Datasource";
import { DatasourceFindManyArgs } from "./DatasourceFindManyArgs";
import { DatasourceWhereUniqueInput } from "./DatasourceWhereUniqueInput";
import { DatasourceUpdateInput } from "./DatasourceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DatasourceControllerBase {
  constructor(
    protected readonly service: DatasourceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Datasource })
  @nestAccessControl.UseRoles({
    resource: "Datasource",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DatasourceCreateInput,
  })
  async createDatasource(
    @common.Body() data: DatasourceCreateInput
  ): Promise<Datasource> {
    return await this.service.createDatasource({
      data: data,
      select: {
        configField: true,
        createdAt: true,
        createdBy: true,
        id: true,
        name: true,
        typeField: true,
        types: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Datasource] })
  @ApiNestedQuery(DatasourceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Datasource",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async datasources(@common.Req() request: Request): Promise<Datasource[]> {
    const args = plainToClass(DatasourceFindManyArgs, request.query);
    return this.service.datasources({
      ...args,
      select: {
        configField: true,
        createdAt: true,
        createdBy: true,
        id: true,
        name: true,
        typeField: true,
        types: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Datasource })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Datasource",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async datasource(
    @common.Param() params: DatasourceWhereUniqueInput
  ): Promise<Datasource | null> {
    const result = await this.service.datasource({
      where: params,
      select: {
        configField: true,
        createdAt: true,
        createdBy: true,
        id: true,
        name: true,
        typeField: true,
        types: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Datasource })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Datasource",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: DatasourceUpdateInput,
  })
  async updateDatasource(
    @common.Param() params: DatasourceWhereUniqueInput,
    @common.Body() data: DatasourceUpdateInput
  ): Promise<Datasource | null> {
    try {
      return await this.service.updateDatasource({
        where: params,
        data: data,
        select: {
          configField: true,
          createdAt: true,
          createdBy: true,
          id: true,
          name: true,
          typeField: true,
          types: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Datasource })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Datasource",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDatasource(
    @common.Param() params: DatasourceWhereUniqueInput
  ): Promise<Datasource | null> {
    try {
      return await this.service.deleteDatasource({
        where: params,
        select: {
          configField: true,
          createdAt: true,
          createdBy: true,
          id: true,
          name: true,
          typeField: true,
          types: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
